### ISSUE TITLE
bignumber error

### ISSUE THREAD

**Issue by priyankanagpal** [nikhilvc1990/AgriChain#5]
Uncaught BigNumber Error: new BigNumber() not a base 16 number: 
    at raise (http://localhost:3000/app.js:40822:25)
    at http://localhost:3000/app.js:40810:33
    at new BigNumber (http://localhost:3000/app.js:39857:28)
    at SolidityTypeDynamicBytes.formatOutputDynamicBytes [as _outputFormatter] (http://localhost:3000/app.js:34336:19)
    at http://localhost:3000/app.js:34877:25
    at SolidityTypeDynamicBytes.SolidityType.decode (http://localhost:3000/app.js:34878:11)
    at http://localhost:3000/app.js:34061:29
    at Array.map (<anonymous>)
    at SolidityCoder.decodeParams (http://localhost:3000/app.js:34060:26)
    at SolidityFunction.unpackOutput (http://localhost:3000/app.js:37228:24)
    at Object.callback (http://localhost:3000/app.js:37256:30)
    at http://localhost:3000/app.js:38208:25
    at http://localhost:3000/app.js:39267:9
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:110497
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9124
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:27347)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:11957
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9124
    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:12233)
    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:12155)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:11957
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:109544

**Comment by nikhilvc1990** [comment]
The problem is that the contract address is not getting generated. Check your blockchain client, use geth or ganache-cli .  https://github.com/Kerala-Blockchain-Academy/AgroChain/blob/master/Important%20Instructions.txt
